[build]
builder = "nixpacks"
buildCommand = "npm install --include=dev && npx medusa build && ls .medusa/server/public/admin/index.html"

[deploy]
preDeployCommand = "npx medusa db:migrate"
startCommand = "cd .medusa/server && npx medusa start"
